### ISSUE TITLE
conmon regression in 2.0.24 causing Kubernetes exec probes in cri-o to fail

### ISSUE THREAD

**Issue by paulnivin** [containers/conmon#244] opened 2021-03-08 01:38 UTC
conmon stopped working in Lyft's environment (Fedora 32 w/ cgroupsV1, Kubernetes 1.16, cri-o tip of 1.16 branch w/ cgroupfs) when https://github.com/containers/conmon/pull/222 landed. Specifically, Kubernetes exec probes now always error out.

Running conmon at 0f092d5446fdadb761b8143b5c4b1d1ac9793f29 results in all exec probes failing with:
```
remote_runtime.go:351] ExecSync [...] from runtime service failed: rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1
```
Building and running conmon at the immediately prior commit of 43377e3bb027e0d358fc07b2283009d751ba4aa0 resolves the issue. I've additionally tested current conmon master at 3ac015ee410f1b05c949b46224b42efbbffbce40 and this commit does not fix this issue. I started looking into conmon changes due to https://github.com/kata-containers/runtime/issues/2352 which had similar error messages.

Historically we haven't pinned conmon and run the version that ships in Fedora. If it's helpful, it looks like the current master branch of cri-o is building against conmon 2.0.20. Let us know if any additional data would be useful.

**Comment by haircommander** [comment] 2021-03-08 14:35
uh oh! can you try with https://github.com/containers/conmon/pull/241? I believe it should fix your problem

**Comment by haircommander** [comment] 2021-03-08 14:36
cri-o has lagged quite a bit, because most of the version churn has been for podman. I will look into bumping conmon in cri-o once we package that PR

**Comment by paulnivin** [comment] 2021-03-08 17:37
Unfortunately, https://github.com/containers/conmon/pull/241 does not resolve the issue. Exec probes with https://github.com/containers/conmon/commit/3ac015ee410f1b05c949b46224b42efbbffbce40 error out in the same manner as with https://github.com/containers/conmon/commit/0f092d5446fdadb761b8143b5c4b1d1ac9793f29.

**Comment by haircommander** [comment] 2021-03-08 17:53
I think https://github.com/containers/conmon/pull/246 may help as well, I was able to reproduce the error and that fixed it

**Comment by paulnivin** [comment] 2021-03-08 18:06
Confirmed that https://github.com/containers/conmon/pull/246 fixes the issue. Thanks!

**Comment by haircommander** [comment] 2021-03-08 18:21
awesome, I'll have 2.0.27 available shortly, probably will make its way into fedora in a couple of days.

In the meantime, we'll test [cri-o with conmon master](https://github.com/cri-o/cri-o/pull/4633) and [test conmon with cri-o integration tests](https://github.com/containers/conmon/pull/245) (two things I've been meaning to do anyway). that should catch the majority of issues earlier.

**Comment by paulnivin** [comment] 2021-03-12 18:49
heads up that koji doesn't yet have a fc32 build

**Comment by haircommander** [comment] 2021-03-12 19:14
oops, thanks, I triggered the build

**Comment by discordianfish** [comment] 2022-02-24 10:52
@haircommander I believe this can be closed, right?

**Comment by saschagrunert** [comment] 2022-02-24 11:42
Yes, closing this one for now.

**Closed by saschagrunert** 2022-02-24 11:42 UTC
